export const menuList = [
    {
        name:"科室首页",
        icon:'icon-shouye',
        children:[
            {
                name:"最新动态",
                path:"#/index/news",
            },
            {
                name:"学术会议",
                path:"#/index/meet",
            },
            {
                name:"研究课题",
                path:"#/index/subject",
            },
            {
                name:"首页轮播",
                path:"#/index/carousel",
            },
        ]
    },
    {
        name:"科室团队",
        icon:'icon-tuandui',
        children:[
            {
                name:"科室管理",
                path:"#/team/department",
            },
            {
                name:"医生管理",
                path:"#/team/doctor",
            }
        ]
    },
    {
        name:"科普宣教",
        icon:'icon-kepu',
        children:[
            {
                name:"分类管理",
                path:"#/education/class",
            },
            {
                name:"文章管理",
                path:"#/education/detail",
            }
        ]
    },
    {
        name:"问题库",
        icon:'icon-biaoqian',
        path:"#/question",
    },
    {
        name:"咨询历史",
        icon:'icon-jian',
        path:"#/consulhistory",
    },
    {
        name:"热门咨询",
        icon:'icon-remen',
        path:"#/consulhot",
    },
    {
        name:"用户管理",
        icon:'icon-guanli',
        children:[
            {
                name:"患者",
                path:"#/UserManager/Patients",
            },
            {
                name:"医学助理",
                path:"#/UserManager/Assistants",
            },
            {
                name:"医生",
                path:"#/UserManager/Doctors",
            }
        ]
    },
    {
        name:"服务记录",
        icon:'icon-jilu',
        path:"#/serive",
    },
    {
        name:"咨询排班",
        icon:'icon-zhibananpai',
        path:"#/arrangement",
    },
    {
        name:"科研库权限",
        icon:'icon-quanxian',
        path:"#/auth",
    }
]