export const PAGEAUTH = {
    allSites: {
        "/summary/view/cumInfRan": ['PM', 'BO', 'BD', 'BDO', 'CRCM'],
        "/summary/view/monInfRam": ['PM', 'BO', 'BD', 'BDO', 'CRCM'],
        "/summary/view/cumFilRan": ['PM', 'BO', 'BD', 'BDO', 'CRCM'],
        "/summary/view/monFilRan": ['PM', 'BO', 'BD', 'BDO', 'CRCM'],
        "/summary/visit/cumVisit": ['PM', 'BO', 'BD', 'BDO', 'CRCM'],
        "/summary/visit/monVisit": ['PM', 'BO', 'BD', 'BDO', 'CRCM'],
        "/summary/site/siteInformed": ['PM', 'BO', 'BD', 'BDO', 'CRCM'],
        "/summary/site/siteFilter": ['PM', 'BO', 'BD', 'BDO', 'CRCM'],
        "/summary/site/siteRandom": ['PM', 'BO', 'BD', 'BDO', 'CRCM'],
        "/summary/fte/cumFTE": ['PM', 'BO', 'BD', 'BDO', 'CRCM'],
        "/summary/fte/monFTE": ['PM', 'BO', 'BD', 'BDO', 'CRCM'],
        "/summary/siteFTE": ['PM', 'BO', 'BD', 'BDO', 'CRCM'],
        "/summary/filter/filterSource": ['PM', 'BO', 'BD', 'BDO', 'CRCM'],
        "/summary/filter/filterReason": ['PM', 'BO', 'BD', 'BDO', 'CRCM'],
        "/plan/degree": ['PA', 'PM', 'BO', 'BD', 'BDO'],
        "/plan/investigation/Type_Informed": ['PA', 'PM', 'BO', 'BD', 'BDO'],
        "/plan/investigation/Type_Filter": ['PA', 'PM', 'BO', 'BD', 'BDO'],
        "/plan/investigation/Type_Random": ['PA', 'PM', 'BO', 'BD', 'BDO'],
        "/plan/site/Type_Informed": ['PA', 'PM', 'BO', 'BD', 'BDO'],
        "/plan/site/Type_Filter": ['PA', 'PM', 'BO', 'BD', 'BDO'],
        "/plan/site/Type_Random": ['PA', 'PM', 'BO', 'BD', 'BDO'],
        "/plan/visitType": ['PA', 'PM', 'BO', 'BD', 'BDO'],
        "/site/detail": ['PA', 'PM', 'BO', 'BD', 'BDO'],
        "/site/pi": ['PA', 'PM', 'BO', 'BD', 'BDO'],
        "/site/cra": ['PA', 'PM', 'BO', 'BD', 'BDO'],
        "/member/crc": ['PA', 'PM', 'BO', 'BD', 'BDO'],
        "/member/require": ['PM', 'BO', 'BD', 'BDO'],
        "/member/distribution": ['PM', 'BO', 'BD', 'BDO'],
        "/executeMgr/manHour": ['PA'],
        "/executeMgr/patients": ['PA'],
        "/executeMgr/crf/Type_Visit": ['PA'],
        "/executeMgr/crf/Type_Pre_Filter": ['PA'],
        "/executeMgr/qa": ['PA'],
        "/executeMgr/site/Type_Site_Start": ['PA'],
        "/executeMgr/site/Type_Site": ['PA'],
        "/executeMgr/crf/Type_Drop": ['PA'],
        "/executeMgr/crf/Type_Violation": ['PA'],
        "/executeMgr/crf/Type_SAE": ['PA'],
        "/executeMgr/transfer": ['PA'],
        "/execute/manHour": ['PM', 'BO', 'CRC', 'BD', 'BDO'],
        "/execute/patients": ['PM', 'BO', 'CRC', 'BD', 'BDO'],
        "/execute/crf/Type_Visit": ['PM', 'BO', 'CRC', 'BD', 'BDO'],
        "/execute/crf/Type_Pre_Filter": ['PM', 'BO', 'CRC', 'BD', 'BDO'],
        "/execute/site/Type_Site_Start": ['PM', 'BO', 'CRC', 'BD', 'BDO'],
        "/execute/site/Type_Site": ['PM', 'BO', 'CRC', 'BD', 'BDO'],
        "/execute/crf/Type_Drop": ['PM', 'BO', 'CRC', 'BD', 'BDO'],
        "/execute/crf/Type_Violation": ['PM', 'BO', 'CRC', 'BD', 'BDO'],
        "/execute/crf/Type_SAE": ['PM', 'BO', 'CRC', 'BD', 'BDO'],
        "/execute/transfer": ['PM', 'BO', 'CRC', 'BD', 'BDO'],
        "/execute/qa": ['PM', 'BO', 'BD', 'BDO'],
        "/sumTotal/summary": ['PM', 'BO', 'BD', 'BDO', 'CRCM'],
        "/sumTotal/efficiency/pro": ['PM', 'BO', 'BD', 'BDO', 'CRCM'],
        "/sumTotal/percent": ['PM', 'BO', 'BD', 'BDO', 'CRCM'],
        "/invContract": ['PA'],
        "/invContractChild": ['PA'],
        "/listContract": ['PM', 'BO', 'BD', 'BDO'],
        "/sumTotal/Monthsum": ['PM', 'BO', 'BD', 'BDO', 'CRCM'],
        "/invDetails": ['PA'],
        "/notice": ['*'],
        "/setting": ['*'],
    },
    detailSite: {
        "/summary/view/cumInfRan": ['PM', 'BO', 'BD', 'BDO', 'CRC', 'CRCC', 'CRCM'],
        "/summary/view/monInfRam": ['PM', 'BO', 'BD', 'BDO', 'CRC', 'CRCC', 'CRCM'],
        "/summary/view/cumFilRan": ['PM', 'BO', 'BD', 'BDO', 'CRC', 'CRCC', 'CRCM'],
        "/summary/view/monFilRan": ['PM', 'BO', 'BD', 'BDO', 'CRC', 'CRCC', 'CRCM'],
        "/summary/visit/cumVisit": ['PM', 'BO', 'BD', 'BDO', 'CRC', 'CRCC', 'CRCM'],
        "/summary/visit/monVisit": ['PM', 'BO', 'BD', 'BDO', 'CRC', 'CRCC', 'CRCM'],
        "/summary/fte/cumFTE": ['PM', 'BO', 'BD', 'BDO', 'CRC', 'CRCC', 'CRCM'],
        "/summary/fte/monFTE": ['PM', 'BO', 'BD', 'BDO', 'CRC', 'CRCC', 'CRCM'],
        "/summary/filter/filterSource": ['PM', 'BO', 'BD', 'BDO', 'CRC', 'CRCC', 'CRCM'],
        "/summary/filter/filterReason": ['PM', 'BO', 'BD', 'BDO', 'CRC', 'CRCC', 'CRCM'],
        "/plan/site/Type_Informed": ['PM', 'BO', 'BD', 'BDO', 'CRC', 'CRCC', 'CRCM'],
        "/plan/site/Type_Filter": ['PM', 'BO', 'BD', 'BDO', 'CRC', 'CRCC', 'CRCM'],
        "/plan/site/Type_Random": ['PM', 'BO', 'BD', 'BDO', 'CRC', 'CRCC', 'CRCM'],
        "/plan/visitType": ['PM', 'BO', 'BD', 'BDO', 'CRC', 'CRCC', 'CRCM'],
        "/site/detail": ['PM', 'BO', 'BD', 'BDO', 'CRC', 'CRCC', 'CRCM'],
        "/site/pi": ['PM', 'BO', 'BD', 'BDO', 'CRC', 'CRCC', 'CRCM'],
        "/site/cra": ['PM', 'BO', 'BD', 'BDO', 'CRC', 'CRCC', 'CRCM'],
        "/member/crc": ['PM', 'BO', 'BD', 'BDO', 'CRC', 'CRCC', 'CRCM'],
        "/member/require": ['PM', 'BO', 'BD', 'BDO', 'CRCC', 'CRCM'],
        "/execute/manHour": ['PM', 'BO', 'BD', 'BDO', 'CRC', 'CRCC', 'CRCM'],
        "/execute/patients": ['PM', 'BO', 'BD', 'BDO', 'CRC', 'CRCC', 'CRCM'],
        "/execute/crf/Type_Visit": ['PM', 'BO', 'BD', 'BDO', 'CRC', 'CRCC', 'CRCM'],
        "/execute/crf/Type_Pre_Filter": ['PM', 'BO', 'BD', 'BDO', 'CRC', 'CRCC', 'CRCM'],
        "/execute/qa": ['PM', 'BO', 'BD', 'BDO', 'CRC', 'CRCC', 'CRCM'],
        "/execute/site/Type_Site_Start": ['PM', 'BO', 'BD', 'BDO', 'CRC', 'CRCC', 'CRCM'],
        "/execute/site/Type_Site": ['PM', 'BO', 'BD', 'BDO', 'CRC', 'CRCC', 'CRCM'],
        "/execute/crf/Type_Drop": ['PM', 'BO', 'BD', 'BDO', 'CRC', 'CRCC', 'CRCM'],
        "/execute/crf/Type_Violation": ['PM', 'BO', 'BD', 'BDO', 'CRC', 'CRCC', 'CRCM'],
        "/execute/crf/Type_SAE": ['PM', 'BO', 'BD', 'BDO', 'CRC', 'CRCC', 'CRCM'],
        "/execute/transfer": ['PM', 'BO', 'BD', 'BDO', 'CRC', 'CRCC', 'CRCM'],
        "/sumTotal/summary": ['PM', 'BO', 'BD', 'BDO', 'CRC', 'CRCC', 'CRCM'],
        "/sumTotal/efficiency/site": ['PM', 'BO', 'BD', 'BDO', 'CRC', 'CRCC', 'CRCM'],
        "/invContract": ['PA'],
        "/invContractChild": ['PA'],
        "/sumTotal/Centremonthsum": ['PM', 'BO', 'BD', 'BDO', 'CRC', 'CRCC', 'CRCM'],
        "/notice": ['*'],
        "/setting": ['*'],
    }
}; 