export const menuList = [
    {
        name:"用户管理",
        icon:'icon-tuandui',
        level:0,
        children:[
            {
                name:"医生",
                path:"#/UserManager/Doctors",
                level:1,
            },
            {
                name:"非医生",
                path:"#/UserManager/NoDoctors",
                level:1,
            },
            {
                name:"临床协调员（内部）",
                path:"#/UserManager/Assistants",
                level:1,
            },
            // {
            //     name:"临床协调员（外部）",
            //     path:"#/UserManager/AssistantsOut",
            //     level:1,
            // }
        ]
    },
    {
        name:"服务管理",
        icon:'icon-guanli',
        level:0,
        children:[
            {
                name:"项目类型",
                path:"#/serive/type",
                level:1,
            },
            {
                name:"授权工作类型",
                path:"#/serive/job",
                level:1,
            },
            {
                name:"服务人员类型",
                path:"#/serive/staff",
                level:1,
            },
        ]
    },
    {
        name:"资费管理",
        icon:'icon-qianbao',
        level:0,
        children:[
            {
                name:"服务单价",
                path:"#/TariffManager/ServicePrice",
                level:1,
            },
            {
                name:"保证金比例",
                path:"#/TariffManager/CapitalRatio",
                level:1,
            },
            {
                name:"平台服务费比例",
                path:"#/TariffManager/ServiceFeeRatio",
                level:1,
            },
        ]
    },
    {
        name:"订单管理",
        icon:'icon-biaoqian',
        path:"#/Order",
        level:0,
        show:true,
        children:[
            {
                name:"订单详情",
                path:"#/OrderDetail/:id",
                level:1,
                show:false,
                back:true,
            }
        ]
    },
    {
        name:"会员制度管理",
        icon:'icon-huiyuan',
        level:0,
        children:[
            {
                name:"等级规则",
                path:"#/Rule/MemberLevel",
                level:1,
            },
            {
                name:"下单会员权益",
                path:"#/Rule/MemberProfit",
                level:1,
            },
            {
                name:"服务会员权益",
                path:"#/Rule/SericeMemberProfit",
                level:1,
            }
        ]
    },
    {
        name:"积分制度管理",
        icon:'icon-jifendingdan',
        level:0,
        children:[
            {
                name:"下单会员积分制度",
                path:"#/Integral/Order",
                level:1,
            },
            {
                name:"服务会员积分制度",
                path:"#/Integral/Serivce",
                level:1,
            }
        ]
    },
    {
        name:"常见问题管理",
        icon:'icon-changjianwenti',
        level:0,
        children:[
            {
                name:"问题分类",
                path:"#/Question",
                level:1,
            },
            {
                name:"问题库",
                path:"#/Question/QuestionList",
                level:1,
                children:[
                    {
                        name:"添加",
                        path:"#/question/save",
                        level:2,
                        show:false,
                        back:true,
                    },
                    {
                        name:"修改",
                        path:"#/question/save/:id",
                        level:2,
                        show:false,
                        back:true,
                    },
                ]
            }
        ]
    },
    {
        name:"留言板管理",
        icon:'icon-banboard1',
        level:0,
        children:[
            {
                name:"留言分类",
                path:"#/Messages/MessagesClass",
                level:1,
            },
            {
                name:"留言记录",
                path:"#/Messages/MessagesList",
                level:1,
            }
        ]
    },
    {
        name:"消息管理",
        icon:'icon-xiaoxi',
        path:"#/Notice",
        level:0,
        show:true,
        children:[
            {
                name:"添加",
                path:"#/Notice/Save",
                level:1,
                show:false,
            },
            {
                name:"修改",
                path:"#/Notice/Save/:id",
                level:1,
                show:false,
            }
        ]
    },
    {
        name:"资金管理",
        icon:'icon-16',
        level:0,
        children:[
            {
                name:"充值明细",
                path:"#/Money/Recharge",
                level:1,
            },
            {
                name:"收入明细",
                path:"#/Money/Revenue",
                level:1,
            },
            {
                name:"提现明细",
                path:"#/Money/Cash",
                level:1,
            },
            {
                name:"订单收支明细",
                path:"#/Money/Order",
                level:1,
            },
            {
                name:"账户查询",
                path:"#/Money/Account",
                level:1,
            }
        ]
    },
    {
        name:"修改密码",
        icon:'icon-biaoqian',
        path:"#/setting",
        level:0,
        show:false,
    }
]